package config_test

import (
	"os"
	"testing"

	"github.com/Bitlatte/evoke/pkg/config"
	"github.com/stretchr/testify/assert"
)

func TestLoadConfig_ParsesEvokeYaml(t *testing.T) {
	// Arrange
	configContent := `
title: "My Awesome Site"
description: "A site generated by Evoke"
`
	os.WriteFile("evoke.yaml", []byte(configContent), 0644)

	// Act
	loadedConfig, err := config.LoadConfig()

	// Assert
	assert.NoError(t, err)
	assert.Equal(t, "My Awesome Site", loadedConfig["title"])
	assert.Equal(t, "A site generated by Evoke", loadedConfig["description"])

	// Clean up
	os.Remove("evoke.yaml")
}
